### 0. 대표적인 데이터분석용 라이브러리
- 넘파이(Numpy) : 넘파이 배열, 리스트 확장판
- 판다스(Pandas) : 테이블형태의 데이터 처리, 딕셔너리의 확장판
- 맷플롯립(Matplotlib) : 파이썬의 시각화를 담당하는 라이브러리
- 외부모듈을 설치할 경우는 파이썬 파이프연산을 통해서 설치한다.
- pip install numpy pandas matplotlib

In [1]:
# list
a = [1, 2, 3, 4, 5]
b = [6, 7, 8, 9, 0]
a+b  # append

[1, 2, 3, 4, 5, 6, 7, 8, 9, 0]

In [2]:
# 라이브러리 로딩
import numpy as np
arr1 = np.array(a)
arr2 = np.array(b)
arr1 + arr2

array([ 7,  9, 11, 13,  5])

In [4]:
print(type(arr1))
print(type(a))

<class 'numpy.ndarray'>
<class 'list'>


In [5]:
len(a)

5

In [6]:
# 넘파일 배열의 크기, shape
arr1.shape

(5,)

In [7]:
ar = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0])
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [8]:
data = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
answer = []
for i in data:
    answer.append(i * 2)
# answer = [i*2 for i in data]    
answer

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [9]:
x = np.array(data)
x * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [10]:
# 벡터화 연산
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

In [11]:
a+b

array([11, 22, 33])

In [12]:
a-b

array([ -9, -18, -27])

In [13]:
a == 2 # 비교연산자와 관계연산자의 결과 True or False

array([False,  True, False])

In [14]:
b > 10

array([False,  True,  True])

In [15]:
(a == 2) & (b > 10) # & : and

array([False,  True, False])

In [16]:
# 2차원 배열 : 행(가로, row)과 열(세로, column)
a = [[0, 1, 2], [3, 4, 5]]
a

[[0, 1, 2], [3, 4, 5]]

In [17]:
c = np.array([[0, 1, 2], [3, 4, 5]])  # 2 x 3 array
c

array([[0, 1, 2],
       [3, 4, 5]])

In [18]:
# 행의 갯수
len(a)

2

In [19]:
len(c)

2

In [20]:
# 열의 갯수
len(c[0])

3

In [21]:
c.shape

(2, 3)

In [22]:
# 3차원 배열 생성 2 x 3 x 4(면, 행, 열)
d = np.array([[[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]],
             [[11, 12, 13, 14],
             [15, 16, 17, 18],
             [19, 20, 21, 22]]])
d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22]]])

In [23]:
# 면, 행, 열
print(len(d), len(d[0]), len(d[0][0]))

2 3 4


In [25]:
# 배열의 차원-ndim과 크기(속성) - shape
d.shape

(2, 3, 4)

In [26]:
d.ndim

3

In [2]:
# 배열의 인덱싱
import numpy as np
a = np.array([0, 1, 2, 3, 4])
a[2]

2

In [3]:
a[-1]

4

In [4]:
b = np.array([[0, 1, 2],[3, 4, 5]])  # 2 x 3
b

array([[0, 1, 2],
       [3, 4, 5]])

In [5]:
#[조건식], [행, 열]
b[0, 0]

0

In [6]:
b[1, 1]

4

In [7]:
# 마지막행 마지막열
b[-1, -1]

5

In [8]:
# 슬라이싱(slicing)
c = np.array([[1, 2, 3, 4],[5, 6, 7, 8]])  # 2 x 4
c

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
# 첫번째행 [행, 열], [시작값:마지막값]
c[0, : ]

array([1, 2, 3, 4])

In [10]:
# 두번째 열 전체
c[:,1]

array([2, 6])

In [11]:
# 두번째 행의 두번째 열부터 끝열까지
c[1, 1:]

array([6, 7, 8])

In [12]:
c[:2, :2]

array([[1, 2],
       [5, 6]])

In [13]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
idx = np.array([True, False, True, False, True,
                False, True, False,True, False])
a[idx]

array([0, 2, 4, 6, 8])

In [14]:
a % 2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

In [15]:
a % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [16]:
a[a%2 == 0]

array([0, 2, 4, 6, 8])

In [19]:
# 넘파이 자료형, type => dtype, 배열의 자료형을 읽어오는 속성
x = np.array([1, 2, 3])
x.dtype
#print(type(x))

dtype('int32')

In [18]:
x = np.array([1.0, 2.0, 3.0])
x.dtype

dtype('float64')

In [20]:
x = np.array([1, 2, 3.0])
x.dtype

dtype('float64')

In [21]:
x

array([1., 2., 3.])

In [23]:
x = np.array([1, 2, 3], dtype = 'f') # f(float)
x.dtype

dtype('float32')

In [27]:
x = np.array([1, 2, 3], dtype = 'U') # u(unsign int), 부호없는 정수
x.dtype

dtype('<U1')

In [28]:
x

array(['1', '2', '3'], dtype='<U1')

In [29]:
# Inf와 NaN
np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  
C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  


array([  0.,  inf, -inf,  nan])

In [30]:
np.log(0)

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


-inf

In [31]:
# 배열 생성 명령 : 단순한 배열을 생성하는 명령어
# zeros, ones
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [32]:
# 배열의 크기 : (행, 열)
b = np.zeros((2, 3))
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [33]:
c = np.zeros((5, 2), dtype = 'i')
c

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [36]:
# 문자열 배열도 가능, 단 모든 원소의 문자열 크기가 같아야 한다.
d = np.zeros(5, dtype='U4')
d

array(['', '', '', '', ''], dtype='<U4')

In [37]:
d[0] = "abc"
d[1] = "abcd"
d[2] = "ABCDE"
d[3] = "ABCDEFGH"
d

array(['abc', 'abcd', 'ABCD', 'ABCD', ''], dtype='<U4')

In [38]:
e = np.ones((2, 3, 4), dtype = 'i')
e

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int32)

In [39]:
# ones_like, zeros_like : 배열의 크기를 명시하지 않고 다른 배열의 크기
f = np.ones_like(b)
f

array([[1., 1., 1.],
       [1., 1., 1.]])

In [40]:
# empty : 배열을 초기화
g = np.empty((4, 3))
g

array([[6.70702901e-312, 2.47032823e-322, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 2.42336543e-057],
       [4.22567128e-090, 2.74072585e-057, 1.55134210e+184],
       [1.39668859e-075, 3.99910963e+252, 1.33536654e+165]])

In [2]:
import numpy as np
# arange : range의 Numpy 버전
np.arange(10) # 0..n-1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.arange(3, 21, 2) # 시작, 끝(포함하지 않음), 증감

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [4]:
# linspace - 선형구간 와 logspace명령 - 로그구간
np.linspace(0, 100, 5)  # 시작, 끝(포함), 갯수

array([  0.,  25.,  50.,  75., 100.])

In [5]:
np.logspace(0.1, 1, 10)

array([ 1.25892541,  1.58489319,  1.99526231,  2.51188643,  3.16227766,
        3.98107171,  5.01187234,  6.30957344,  7.94328235, 10.        ])

In [6]:
# 전치연산 : 행과 열을 바꾸는 기능, T
A = np.array([[1, 2, 3], [4, 5, 6]])  # 2 x 3
A

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
A.T  # 3 x 2

array([[1, 4],
       [2, 5],
       [3, 6]])

In [9]:
# 배열의 크기 변형
# shape : 배열의 속성 확인
# reshape(행, 열)
a = np.arange(12) # 0 ~ 11
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [11]:
b = a.reshape(3, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [12]:
a.reshape(3, -1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [13]:
a.reshape(2, 2, -1)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [14]:
a.reshape(2, -1, 2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [15]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [16]:
x.reshape(1, 5)

array([[0, 1, 2, 3, 4]])

In [17]:
x.reshape(5, 1)

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [18]:
# 벡터(Vector)화 연산
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])

In [19]:
a + b

array([5, 4, 5, 8])

In [20]:
a - b

array([-3,  0,  1,  0])

In [21]:
a * b

array([ 4,  4,  6, 16])

In [22]:
a / b

array([0.25, 1.  , 1.5 , 1.  ])

In [23]:
a == b

array([False,  True, False,  True])

In [24]:
a >= b

array([False,  True,  True,  True])

In [25]:
# all() : 모든 요소를 대상으로 비교하는 작업
np.all(a == b)

False

In [26]:
c = np.array([1, 2, 3, 4])
np.all(a == c)

True

In [27]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
x * 100

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [29]:
x = np.arange(12).reshape(3, 4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [30]:
100 * x

array([[   0,  100,  200,  300],
       [ 400,  500,  600,  700],
       [ 800,  900, 1000, 1100]])

In [31]:
# 내장함수
# min, max, sum, mean, median, std, var, all, any

In [32]:
x = np.array([1, 2, 3, 4])
x

array([1, 2, 3, 4])

In [33]:
np.sum(x)

10

In [34]:
# argmin-최솟값의 위치, argmax-최대값의 위치
np.min(x)

1

In [35]:
np.argmin(x)

0

In [36]:
np.max(x)

4

In [37]:
np.argmax(x)

3

In [38]:
x.mean()  # 평균

2.5

In [39]:
np.mean(x)

2.5

In [40]:
np.median(x)

2.5

In [41]:
np.all([True, True, False])

False

In [42]:
np.any([True, True, False])

True

In [43]:
x = np.array([[1, 2], [3, 4]])
x

array([[1, 2],
       [3, 4]])

In [44]:
np.sum(x) 

10

In [45]:
x.sum()

10

In [46]:
x.sum(axis=0)  # 열

array([4, 6])

In [48]:
x.sum(axis=1)  # 행

array([3, 7])

In [49]:
a = np.array([[1, 2], [3,4]], dtype = "i")
b = np.array([[1, 2], [3,4]], dtype = "i")

In [50]:
a

array([[1, 2],
       [3, 4]], dtype=int32)

In [51]:
b

array([[1, 2],
       [3, 4]], dtype=int32)

In [52]:
a+b

array([[2, 4],
       [6, 8]], dtype=int32)

In [53]:
a-b

array([[0, 0],
       [0, 0]], dtype=int32)

In [54]:
a/b

array([[1., 1.],
       [1., 1.]])

In [55]:
a*b

array([[ 1,  4],
       [ 9, 16]], dtype=int32)