In [10]:
from sklearn.datasets import load_iris
iris = load_iris()

In [2]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [4]:
iris['data'].shape

(150, 4)

In [5]:
iris['target'].shape

(150,)

In [6]:
iris['target_names']

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [7]:
iris['feature_names']

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [11]:
from sklearn.model_selection import train_test_split
X = iris['data']
y = iris['target']

X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y,test_size=0.2, random_state=42)

In [12]:
print(X_train.shape, X_test.shape)

(120, 4) (30, 4)


In [13]:
import numpy as np
np.unique(y_train, return_counts=True)

(array([0, 1, 2]), array([40, 40, 40], dtype=int64))

In [14]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=1)

In [15]:
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=1)

In [16]:
pred = knn.predict(X_test)
pred

array([0, 2, 1, 1, 0, 1, 0, 0, 2, 1, 2, 2, 2, 1, 0, 0, 0, 1, 1, 1, 0, 2,
       1, 2, 2, 1, 1, 0, 2, 0])

In [17]:
np.mean(pred == y_test)

0.9666666666666667

In [18]:
from sklearn.tree import DecisionTreeClassifier

tree = DecisionTreeClassifier()

tree.fit(X_train, y_train)

DecisionTreeClassifier()

In [19]:
pred2 = tree.predict(X_test)
pred2

array([0, 2, 1, 1, 0, 1, 0, 0, 2, 1, 2, 2, 2, 1, 0, 0, 0, 1, 1, 2, 0, 2,
       1, 1, 2, 2, 1, 0, 2, 0])

In [20]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, pred2)

0.9333333333333333

In [21]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()
lr.fit(X_train, y_train)

LogisticRegression()

In [22]:
from sklearn.model_selection import cross_val_score

cross_val_score(lr, X_test, y_test, cv=10).mean()

0.9333333333333332

In [23]:
from sklearn.svm import SVC

svc = SVC()
svc.fit(X_train, y_train)

SVC()

In [24]:
cross_val_score(svc, X_test, y_test, cv=10).mean()

0.9333333333333332

In [26]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train, y_train)

cross_val_score(gnb, X_test, y_test, cv=10).mean()

0.9

In [27]:
from sklearn.datasets import load_iris
iris = load_iris()

train_input, test_input, train_target, test_target = train_test_split(X, y, test_size=0.2, random_state=42)

In [28]:
print(train_input.shape, train_target.shape)

(120, 4) (120,)


In [29]:
print(test_input.shape, test_target.shape)

(30, 4) (30,)


In [30]:
from tensorflow import keras

sc = SGDClassifier(loss='log', max_iter=5, random_state=42)
scores =  cross_validate(sc, train_input, train_target, n_jobs=-1)
print(np.mean(scores['test_score']))

NameError: name 'SGDClassifier' is not defined