In [ ]:
# count : 데이터 개수
# 평균 : mean, average
# 분산 : var, variance
# 표준편차 : std, standart deviation
# 최대값 : maximum
# 최소값 : minimum
# 중앙값 : median
# 사분위수 : quartile

In [3]:
import numpy as np
x = np.array([18, 5, 10, 23, 19, -8, 10, 0, 5, 2, 
              15, 8, 2, 5, 4, 15, -1, 4, -7, -24,
             7, 9, -6, 23, -13])
x

array([ 18,   5,  10,  23,  19,  -8,  10,   0,   5,   2,  15,   8,   2,
         5,   4,  15,  -1,   4,  -7, -24,   7,   9,  -6,  23, -13])

In [4]:
len(x)

25

In [5]:
np.mean(x)

5.0

In [6]:
np.var(x)

118.88

In [7]:
np.std(x)

10.903210536351208

In [8]:
np.max(x)

23

In [9]:
np.min(x)

-24

In [10]:
np.median(x)

5.0

In [11]:
# 백분위수(percentile)
np.percentile(x, 0)  # 최소값

-24.0

In [12]:
np.percentile(x, 100)  # 최대값

23.0

In [13]:
np.percentile(x, 25)  # 1사분위수

0.0

In [14]:
np.percentile(x, 50)  # 2사분위수

5.0

In [15]:
np.percentile(x, 75)  # 3사분위수

10.0

In [17]:
# 난수 발생
# rand() : 0과 1사이의 난수를 발생시키는 함수
np.random.rand(5)

array([0.45012155, 0.84043889, 0.49340437, 0.48538393, 0.87969944])

In [18]:
np.random.rand(10)

array([0.79225735, 0.13140972, 0.66296763, 0.72879047, 0.0024611 ,
       0.40016179, 0.18035941, 0.19620351, 0.4630293 , 0.00744075])

In [19]:
np.random.rand(10)

array([0.8190762 , 0.78516121, 0.22505151, 0.81091657, 0.93187576,
       0.96938003, 0.141075  , 0.96651427, 0.90995363, 0.63613654])

In [20]:
# shuffle() : 데이터를 섞는다.
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.random.shuffle(x)
x

array([2, 9, 8, 5, 7, 3, 0, 6, 1, 4])

In [24]:
np.random.choice(5, 5)

array([0, 2, 2, 3, 3])

In [25]:
np.random.choice(5, 5, replace=False)

array([1, 0, 4, 2, 3])

In [26]:
np.random.choice(5, 10, p = [0.1, 0, 0.3, 0.6, 0] )

array([2, 3, 2, 3, 2, 3, 2, 2, 3, 2], dtype=int64)

In [ ]:
# rand : 0부터 1사이의 균일 분포
# randn : 표준 정규 분포
# randint : 균일 분포의 정수 난수

In [28]:
np.random.rand(10)

array([0.29630055, 0.47703524, 0.59033091, 0.04521424, 0.09374338,
       0.07547732, 0.79543534, 0.44505323, 0.98605699, 0.00542255])

In [29]:
np.random.rand(3, 5)  # 3행 5열, (행, 열)

array([[0.53292474, 0.72076804, 0.75424536, 0.32552458, 0.02776178],
       [0.78462156, 0.91407202, 0.73533323, 0.47083397, 0.19950895],
       [0.88478423, 0.92141814, 0.64868135, 0.49411278, 0.68677414]])

In [30]:
np.random.randn(10)

array([ 1.99218185, -0.56591072,  1.10471978, -0.69823823,  1.92995325,
        1.59325395,  0.51101598,  0.74661002, -0.56169141, -0.59324798])

In [31]:
np.random.randn(3, 5)

array([[-0.53085469,  0.14988169,  0.722773  , -0.11138891,  1.07206029],
       [ 1.3029254 ,  1.66757382,  0.27379322,  0.52868494, -0.64427777],
       [ 0.09838329,  0.69087921, -0.48138403, -0.36308009, -0.4500288 ]])

In [32]:
# randint(low, high, size)
np.random.randint(10, size=10)

array([7, 8, 8, 1, 7, 3, 4, 3, 5, 1])

In [33]:
np.random.randint(10,20, size=10)

array([13, 11, 12, 10, 11, 14, 11, 10, 16, 13])

In [34]:
np.random.randint(10,20, size=(3, 5))

array([[12, 12, 18, 18, 15],
       [18, 18, 13, 12, 19],
       [12, 16, 14, 18, 18]])